import SwiftUI

struct WellnessReportView: View {
    let data: WellnessReportData

    var body: some View {
        VStack(alignment: .leading, spacing: 0) {
            headerSection
            Divider()
            statsGrid
            footerSection
        }
        .frame(width: 390)
        .background(Color(.systemBackground))
    }

    // MARK: - Header

    private var headerSection: some View {
        HStack {
            VStack(alignment: .leading, spacing: 2) {
                Text("WellPlate")
                    .font(.r(.headline, .semibold))
                    .foregroundColor(AppColors.brand)
                Text("Weekly Wellness Report")
                    .font(.r(.caption, .regular))
                    .foregroundColor(AppColors.textSecondary)
            }
            Spacer()
            Text(data.dateRange)
                .font(.r(.caption2, .regular))
                .foregroundColor(AppColors.textSecondary)
        }
        .padding(.horizontal, 20)
        .padding(.vertical, 16)
        .background(AppColors.brand.opacity(0.06))
    }

    // MARK: - Stats Grid

    private var statsGrid: some View {
        LazyVGrid(columns: [GridItem(.flexible()), GridItem(.flexible())], spacing: 1) {
            statTile(icon: "brain.head.profile",
                     label: "Avg Stress",
                     value: data.avgStressScore.map { "\(Int($0))/100" } ?? "—",
                     color: stressColor)
            statTile(icon: "flame.fill",
                     label: "Avg Calories",
                     value: "\(Int(data.avgCalories)) / \(data.calorieGoal)",
                     color: Color(hex: "FF6B35"))
            statTile(icon: "figure.walk",
                     label: "Avg Steps",
                     value: data.avgSteps > 0 ? "\(Int(data.avgSteps).formatted())" : "—",
                     color: .blue)
            statTile(icon: "drop.fill",
                     label: "Avg Water",
                     value: "\(Int(data.avgWaterGlasses.rounded())) / \(data.waterGoal) cups",
                     color: Color(hex: "5E9FFF"))
            statTile(icon: "face.smiling",
                     label: "Top Mood",
                     value: data.dominantMoodEmoji,
                     color: .yellow)
            statTile(icon: "checkmark.circle.fill",
                     label: "Days Logged",
                     value: "\(data.loggedDays) / 7",
                     color: .green)
        }
        .background(Color(.separator).opacity(0.2))
    }

    private func statTile(icon: String, label: String, value: String, color: Color) -> some View {
        VStack(alignment: .leading, spacing: 6) {
            HStack(spacing: 5) {
                Image(systemName: icon)
                    .font(.system(size: 11, weight: .semibold))
                    .foregroundColor(color)
                Text(label)
                    .font(.r(.caption2, .medium))
                    .foregroundColor(AppColors.textSecondary)
                    .textCase(.uppercase)
                    .kerning(0.3)
            }
            Text(value)
                .font(.r(.subheadline, .semibold))
                .foregroundColor(AppColors.textPrimary)
                .lineLimit(1)
                .minimumScaleFactor(0.8)
        }
        .padding(.horizontal, 16)
        .padding(.vertical, 14)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(Color(.systemBackground))
    }

    private var stressColor: Color {
        guard let score = data.avgStressScore else { return AppColors.textSecondary }
        switch score {
        case ..<40:  return .green
        case ..<60:  return .yellow
        case ..<80:  return .orange
        default:     return .red
        }
    }

    // MARK: - Footer

    private var footerSection: some View {
        Text("Generated by WellPlate · Data stays on your iPhone")
            .font(.r(.caption2, .regular))
            .foregroundColor(AppColors.textSecondary.opacity(0.6))
            .frame(maxWidth: .infinity, alignment: .center)
            .padding(.vertical, 10)
            .background(Color(.secondarySystemBackground))
    }
}
